{
 "title": "Speedtest",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Avg Upload",
   "type": "stat",
   "description": "Average upload speed",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"upload\")\r\n  |> filter(fn: (r) => r._field == \"bandwidth\")\r\n"
    }
   ]
  },
  {
   "title": "Speedtest Results",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"speeds\")\r\n  |> filter(fn: (r) => r._field == \"bandwidth_down\")"
    },
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"speeds\")\r\n  |> filter(fn: (r) => r._field == \"bandwidth_up\")"
    }
   ]
  },
  {
   "title": "Download Size Total",
   "type": "stat",
   "description": "Shows cumulative download size for speedtests",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"download\")\r\n  |> filter(fn: (r) => r._field == \"bytes\")"
    }
   ]
  },
  {
   "title": "Upload Size Total",
   "type": "stat",
   "description": "Shows cumulative upload size for speedtests",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"upload\")\r\n  |> filter(fn: (r) => r._field == \"bytes\")"
    }
   ]
  },
  {
   "title": "Avg Download",
   "type": "stat",
   "description": "Average download speed",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"download\")\r\n  |> filter(fn: (r) => r._field == \"bandwidth\")"
    }
   ]
  },
  {
   "title": "Avg Test Latency",
   "type": "stat",
   "description": "Ping time from speedtest servers",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ping\")\r\n  |> filter(fn: (r) => r._field == \"latency\")\r\n  "
    }
   ]
  },
  {
   "title": "High Frequency Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"pings\")\r\n  |> filter(fn: (r) => r._field == \"rtt\")\r\n  |> group(columns: [\"target\"])\r\n  |> rename(columns: {_value: \"Latency\"})\r\n"
    }
   ]
  },
  {
   "title": "Avg Ping Latency",
   "type": "stat",
   "description": "Ping time to google/cloudflare",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"pings\")\r\n  |> filter(fn: (r) => r._field == \"rtt\")"
    }
   ]
  },
  {
   "title": "Avg Test Time",
   "type": "stat",
   "description": "Time required for a single speedtest",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"speeds\")\r\n  |> filter(fn: (r) => r._field == \"elapsed_down\")\r\n"
    },
    {
     "query": "from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"speeds\")\r\n  |> filter(fn: (r) => r._field == \"elapsed_up\")"
    }
   ]
  },
  {
   "title": "Avg Speed by Test Server",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "download_avg = from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"download\")\r\n  |> filter(fn: (r) => r._field == \"bandwidth\")\r\n  |> group(columns: [\"server_id\", \"server_name\", \"server_location\"])\r\n  |> mean()\r\n  |> rename(columns: {_value: \"Download Avg\"})\r\n  |> limit(n: 100)\r\n\r\nupload_avg = from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"upload\")\r\n  |> filter(fn: (r) => r._field == \"bandwidth\")\r\n  |> group(columns: [\"server_id\", \"server_name\", \"server_location\"])\r\n  |> mean()\r\n  |> rename(columns: {_value: \"Upload Avg\"})\r\n  |> limit(n: 100)\r\n\r\nstep1 = join(tables: {da: download_avg, ua: upload_avg}, on: [\"server_id\"])\r\n  |> keep(columns: [\"server_id\", \"server_name_da\", \"server_location_da\", \"Download Avg\", \"Upload Avg\"])\r\n\r\ndownload_count = from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"download\")\r\n  |> filter(fn: (r) => r._field == \"bandwidth\")\r\n  |> group(columns: [\"server_id\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"Test Count\"})\r\n  |> limit(n: 100)\r\n\r\nping_avg = from(bucket: \"speedtest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ping\")\r\n  |> filter(fn: (r) => r._field == \"latency\")\r\n  |> group(columns: [\"server_id\"])\r\n  |> mean()\r\n  |> rename(columns: {_value: \"Ping\"})\r\n  |> limit(n: 100)\r\n\r\nstep2 = join(tables: {dc: download_count, pa: ping_avg}, on: [\"server_id\"])\r\n  |> keep(columns: [\"server_id\", \"Test Count\", \"Ping\"])\r\n\r\njoin(tables: {s1: step1, s2: step2}, on: [\"server_id\"])\r\n  |> keep(columns: [\"server_id\", \"server_name_da\", \"server_location_da\", \"Download Avg\", \"Upload Avg\", \"Test Count\", \"Ping\"])\r\n"
    }
   ]
  }
 ]
}